### ISSUE TITLE
How do I change menu items once the new SysTray object has been created?

### ISSUE THREAD

**Issue by MikeHibbert** [zaaack/node-systray#13]
I'm creating menu items that only display if the user authenticates.

How can I show a set of "logged out" and "logged in" menu options once the SysTray object is created?

Is it just a case of detroying the object and creating the icon again? if so how do I do that without closing the app?

**Comment by zaaack** [comment]
@MikeHibbert You can use `sendAction` to update single item or whole menu, e.g.

```ts

systray.onClick(action => {
    if (action.seq_id === 0) { // first menu item
        systray.sendAction({ // update current menu item 
            type: 'update-item', 
            item: {
              ...action.item,
              title: 'logged out', 
            },
            seq_id: action.seq_id,
        })
    } 
})


```
