### ISSUE TITLE
No icon image is visible in the systray

### ISSUE THREAD

**Issue by alinnert** [zaaack/node-systray#2]
I'm using Windows 10 (1709). I'm trying out this library but so far I can't see an icon in the systray. There is an entry being added to the systray though. If I click on it the menu I defined shows up. So technically it's working fine. But the systray entry is empty, the icon is invisible.

I've also tried to use the string that's being used in this file:
https://github.com/zaaack/node-systray/blob/master/test/menu.json
But it makes no difference.

I'm afraid that some cache could be involved here and some incorrect icon string is being cached now from when I started the app for the first time. I've already restarted my laptop but that didn't help.

Do you know what that could be and how this can be fixed? Or is it not working in general?

**Comment by zaaack** [comment]
You can see more docs in go systray library, which under the hood. In windows you should using .ico format for icons, The icon format in test folder is .png, which can work in linux/macos.

**Comment by alinnert** [comment]
Ah, great. Converting the png to ico and using that instead works. Thank you.
