### ISSUE TITLE
Not working on High Sierra

### ISSUE THREAD

**Issue by bromagosa** [zaaack/node-systray#3]
Hi! I'm using your module for a little application, and it's working perfectly on Linux and Windows, but it fails in MacOS High Sierra (works in El Capitan).

I've recompiled your systray-portable package and I found out you now need to pass an additional `onExit` function to `systray.Run()` in order for it to compile.

That seems to not be enough though, as it still fails with a different error now:

```
[...]
at SysTray.writeLine (node_modules/systray/lib/index.js:184:9)
at SysTray.sendAction (node_modules/systray/lib/index.js:208:12)
[...]
```

Any chance to get a working version for the latest MacOS?

Let me know how if I can help.

**Comment by bromagosa** [comment]
Got it, the issue was that `debug` is not supported anymore as an option.

I can send you a PR with the freshly compiled binaries for High Sierra if you want to update them :)

**Comment by zaaack** [comment]
@bromagosa Thanks for your digging! I haven't upgraded my macOS to High Sierra yet, so I cannot reproduce it quickly. Feel free to send a PR If it's urgent.

**Comment by bromagosa** [comment]
@zaaack thanks! Just sent a PR :)

Let me know if it's all good!
